# CMake script to generate version.h

# Find Git
find_package(Git QUIET)

set(VERSION_STRING "v${PROJECT_VERSION}")

if(GIT_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} describe --tags --always --dirty
        WORKING_DIRECTORY "${SOURCE_DIR}"
        RESULT_VARIABLE GIT_RESULT
        OUTPUT_VARIABLE GIT_OUT
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(GIT_RESULT EQUAL 0 AND NOT GIT_OUT STREQUAL "")
        # Ensure we prepend 'v' if git describe returned a hash or raw version without it
        if(NOT GIT_OUT MATCHES "^v")
            set(VERSION_STRING "v${GIT_OUT}")
        else()
            set(VERSION_STRING "${GIT_OUT}")
        endif()
    endif()
endif()

# File path to generate
set(HEADER_PATH "${BINARY_DIR}/generated/include/orbit/version.h")

# C23-compliant version header contents using East Const
set(HEADER_CONTENT "/*
 * Generated by CMake. Do not edit.
 */
#pragma once

constexpr char const ORBIT_VERSION[] = \"${VERSION_STRING}\";
constexpr char const ORBIT_BUILD_DATE[] = __DATE__;
constexpr char const ORBIT_BUILD_TIME[] = __TIME__;
")

# Check if file exists and has same content to avoid invalidating builds
set(WRITE_FILE TRUE)
if(EXISTS "${HEADER_PATH}")
    file(READ "${HEADER_PATH}" EXISTING_CONTENT)
    if(EXISTING_CONTENT STREQUAL HEADER_CONTENT)
        set(WRITE_FILE FALSE)
    endif()
endif()

if(WRITE_FILE)
    file(WRITE "${HEADER_PATH}" "${HEADER_CONTENT}")
    message(STATUS "Generated/Updated version.h: ${VERSION_STRING}")
endif()
